language: python
sudo: false

cache:
  pip: true
  directories:
    - here

env:
  global:
    - RDB_VER="2.3.5~0"
  matrix:
     - |
       LUA="lua 5.1"
       LUA_PATH="lua51"
     - |
       LUA="lua 5.2"
       LUA_PATH="lua52"
     - |
       LUA="lua 5.3"
       LUA_PATH="lua53"
       RDB_VER="2.3.4~0"
     - |
       LUA="luajit 2.0"
       LUA_PATH="jit20"
     - |
       LUA="luajit 2.1"
       LUA_PATH="jit21"

before_install:
  - pip install hererocks
  - hererocks here/$LUA_PATH -r^ --$LUA
  - source here/$LUA_PATH/bin/activate
  - luarocks install luacheck
  - luacheck src
  # Fix from https://github.com/leafo/lapis/issues/6
  - luarocks install https://gist.githubusercontent.com/starius/b20d3e63929ae678c857/raw/4b4499f442337b6f577422364358590bd00c9d48/luacrypto-0.3.2-2.rockspec

install:
  - luarocks build --only-deps lua-reql-1.0.2-0.rockspec

before_script:
  - wget https://download.rethinkdb.com/apt/pool/precise/main/r/rethinkdb/rethinkdb_${RDB_VER}precise_amd64.deb
  - ar x rethinkdb_${RDB_VER}precise_amd64.deb
  - tar xvzf data.tar.gz
  - ./usr/bin/rethinkdb --daemon
  - luarocks install busted
  - luarocks install luacov-coveralls

script:
  - busted --exclude-tags="expensive"

before_cache:
  - rm -rf $HOME/.cache/pip/log

after_success:
  - luacov-coveralls
